### ISSUE TITLE
Random contributions

### ISSUE THREAD

**Issue by AntonioND** [avivace/awesome-gbdev#1]
I hadn't seen this before. You have linked to a few of my projects, but I have a few more GB-related:

Demo:
https://github.com/AntonioND/back-to-color

Games:
https://github.com/AntonioND/geometrix
https://github.com/AntonioND/bitcity

Development:
https://github.com/AntonioND/gbt-player

Documentation:
https://github.com/AntonioND/gbcam-rev-engineer

**Comment by avivace** [comment]
Good job. I've added what you suggested.
