### ISSUE TITLE
Reiner Ziegler 

### ISSUE THREAD

**Issue by vmsh0** [avivace/awesome-gbdev#101]
Does anyone have a backup of the page w/ photos? The website has sadly gone offlisn

**Comment by nitro2k01** [comment]
I have mirrored the site. Reiner also replied: "just saved the domain, content is gone ... sorry"
I said I mirrored and offered to give him the files to restore the site. No reply yet. 
There's also a mirror by Archive Team. All relevant links are below:

Live mirror: http://reinerziegler.de.mirrors.gg8.se/
Site rip, mine: http://reinerziegler.de.mirrors.gg8.se/reinerziegler.de.tar.gz
Site rip, Archive Team: https://archive.org/details/warc-www_reinerziegler_de

**Comment by vmsh0** [comment]
Thanks. That's nice to hear.

I can offer hosting for him if he wants to restore. :)

Il 07 giu 2018 00:39, nitro2k01 <notifications@github.com> ha scritto:

I have mirrored the site. Reiner also replied: "just saved the domain, content is gone ... sorry"
I said I mirrored and offered to give him the files to restore the site. No reply yet.
There's also a mirror by Archive Team. All relevant links are below:

Live mirror: http://reinerziegler.de.mirrors.gg8.se/
Site rip, mine: http://reinerziegler.de.mirrors.gg8.se/reinerziegler.de.tar.gz
Site rip, Archive Team: https://archive.org/details/warc-www_reinerziegler_de

**Comment by avivace** [comment]
I've replaced the dead link with the mirror provided by @nitro2k01 .
The [reinerziegler](https://github.com/gb-archive/reinerziegler) repository in our _Game Boy Archive_ project now hosts an additional copy of the site rip, just to be sure.

We should be good
