### ISSUE TITLE
Some resources

### ISSUE THREAD

**Issue by pepijndevos** [avivace/awesome-gbdev#61]
I tried to create a PR via GitHub but twice in a row it ended up adding/removing additional lines, so I'll just suggest them here:

- [Introduction to Game Boy Hacking](http://pepijndevos.nl/sha2017/workshop.pdf) - Workshop introducing basic assembly, debugging and reverse engineering.
- [Game Boy Assembly Language Primer](http://www.devrs.com/gb/files/galp.zip) - Simple template code with memory defines, copy routines and IBM font tilemap.

**Comment by avivace** [comment]
Oh, no problem at all.
I just pushed your additions, thank you!
