### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by tobiasvl** [avivace/awesome-gbdev#67]
This project is licensed under the GPL-3.0. [That's fine](https://www.gnu.org/licenses/gpl-faq.en.html#GPLOtherThanSoftware) in itself, but there's a big issue with this choice.

**We don't have the legal right** to license the [salvaged articles](https://github.com/avivace/awesome-gbdev/tree/master/articles/salvage) under GPL. (We don't really have the right to distribute them either, but I think that's of lesser consequence than licensing them with a copyleft license.)

Solving this is probably as simple as writing somewhere (in `LICENSE`, maybe) that the files in the `articles/salvage/` directory are not licensed under GPL. We never had the right to license them, so clarifying that fact should really be all that's needed. I think.

**Comment by avivace** [comment]
We can move the salvaged articles to a dedicated repository in *The Game Boy Archive* project, and maybe offer a frontend/ftp-archive-like access, providing a clear statement and disclaimer about the various sources and license terms.

**Comment by avivace** [comment]
Okay, the repo is [here](https://github.com/gb-archive/salvage). We need a disclaimer there about the licensing issue making clear that they are non homogenous contributions from different context/licensing permissions/authors.

Anyway, we're clear in this repository.
