### ISSUE TITLE
Re-order emulators into their own section?

### ISSUE THREAD

**Issue by davidsharp** [avivace/awesome-gbdev#7]
Going through the list I noticed a few places where emulators are mentioned amongst tools, but also some in the misc-like section at the bottom.

I feel that there are enough links, that are also nicely varied, to belong in their own section.

Again, I'd be happy to do this.

**Comment by avivace** [comment]
Makes sense. 
The main issue here is the _scope_ of emulators: some of them are _tools_ (providing advanced debugging, detailed hardware emulation and checks), some others are very useful in studying the hardware architecture and actual functionality, or understanding how hardware mechanics are implemented in various languages and technologies (e.g. PHP terminal emulator, or JS).
