### ISSUE TITLE
Many links broken by search/replace

### ISSUE THREAD

**Issue by yupferris** [avivace/awesome-gbdev#8]
Looks like in 573b31c3e5b739ec097736a3b1bc9365260e74ef, there was a search/replace from "gameboy" to "Game Boy" in `README.md`, which broke many links, such as [Game Boy Demospotting](http://game%20boy.modermodemet.se/en) (should be http://gameboy.modermodemet.se/), etc. I don't want to just revert the commit and fix those as it looks like there were a lot of other useful changes in that commit, but it needs to be gone through so these links can be fixed. I suggest the commit author take this task, but I wouldn't mind doing it myself either :)

**Comment by avivace** [comment]
Woops! Thanks for letting me know. (Almost) every link should be back now.

**Comment by yupferris** [comment]
Looks like it, nice one :)
